name: Extension Method

# Accepts 'flutter' or 'dart'
type: flutter

# Configuration for each step
steps:
  - name: Step 1
    directory: step_01
    has_solution: false
  - name: Step 2
    directory: step_02
    has_solution: false
  - name: Step 3
    directory: step_03
    has_solution: false
  - name: Step 4
    directory: step_04